### ISSUE TITLE
JSON Format 

### ISSUE THREAD

**Issue by AlexCrominus** [Remus7/Percentage#2]
`{
    name: String,
    glass: String,
    ingredients: [
        "ex1",
        "ex2",
        "ex3"
    ]
    preparation: String
}`

**Comment by Remus7** [comment]
JSON
{
"margherita": { "glass": "type", "ingredients": ["1", "2", "3"], "preparation": "type" },
"green_apple": { "glass": "type", "ingredients": ["1", "2", "3"], "preparation": "type" },
"pina_colada": { "glass": "type", "ingredients": ["1", "2", "3"], "preparation": "type" }
}
